
export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING';
export const USER_REGISTER_RESOLVE = 'USER_REGISTER_RESOLVE';
export const USER_REGISTER_REJECT = 'USER_REGISTER_REJECT';

export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_RESOLVE = 'USER_LOGIN_RESOLVE';
export const USER_LOGIN_REJECT = 'USER_LOGIN_REJECT';

export const USER_LOGOUT = 'USER_LOGOUT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
