// USER AUTH
export const USER_REGISTER_PENDING = "USER_REGISTER_PENDING";
export const USER_REGISTER_RESOLVE = "USER_REGISTER_RESOLVE";
export const USER_REGISTER_REJECT = "USER_REGISTER_REJECT";

export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_RESOLVE = "USER_LOGIN_RESOLVE";
export const USER_LOGIN_REJECT = "USER_LOGIN_REJECT";

export const USER_LOGOUT = "USER_LOGOUT";

export const SET_CURRENT_USER = "SET_CURRENT_USER";


// USER PROFILE
export const GET_PROFILE_PENDING = "GET_PROFILE_PENDING";
export const GET_PROFILE_RESOLVE = "GET_PROFILE_RESOLVE";
export const GET_PROFILE_REJECT = "GET_PROFILE_REJECT";

export const GET_ALL_PROFILE_PENDING = "GET_ALL_PROFILE_PENDING";
export const GET_ALL_PROFILE_RESOLVE = "GET_ALL_PROFILE_RESOLVE";
export const GET_ALL_PROFILE_REJECT = "GET_ALL_PROFILE_REJECT";

export const CLEAR_CURRENT_USER_PROFILE = "CLEAR_CURRENT_USER_PROFILE";

export const CREATE_PROFILE_PENDING = "CREATE_PROFILE_PENDING";
export const CREATE_PROFILE_RESOLVE = "CREATE_PROFILE_RESOLVE";
export const CREATE_PROFILE_REJECT = "CREATE_PROFILE_REJECT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const EDIT_PROFILE_PENDING = "EDIT_PROFILE_PENDING";
export const EDIT_PROFILE_RESOLVE = "EDIT_PROFILE_RESOLVE";
export const EDIT_PROFILE_REJECT = "EDIT_PROFILE_REJECT";

export const REFETCH_USER_PROFILE = "REFETCH_USER_PROFILE";

export const ADD_USER_EXPERIENCE_PENDING = 'ADD_USER_EXPERIENCE_PENDING';
export const ADD_USER_EXPERIENCE_RESOLVE = 'ADD_USER_EXPERIENCE_RESOLVE';
export const ADD_USER_EXPERIENCE_REJECT = 'ADD_USER_EXPERIENCE_REJECT';

export const ADD_USER_EDUCATION_PENDING = 'ADD_USER_EDUCATION_PENDING';
export const ADD_USER_EDUCATION_RESOLVE = 'ADD_USER_EDUCATION_RESOLVE';
export const ADD_USER_EDUCATION_REJECT = 'ADD_USER_EDUCATION_REJECT';

export const DELETE_USER_EDUCATION_PENDING = 'DELETE_USER_EDUCATION_PENDING';
export const DELETE_USER_EDUCATION_RESOLVE = 'DELETE_USER_EDUCATION_RESOLVE';
export const DELETE_USER_EDUCATION_REJECT = 'DELETE_USER_EDUCATION_REJECT';

export const DELETE_USER_EXPERIENCE_PENDING = 'DELETE_USER_EXPERIENCE_PENDING';
export const DELETE_USER_EXPERIENCE_RESOLVE = 'DELETE_USER_EXPERIENCE_RESOLVE';
export const DELETE_USER_EXPERIENCE_REJECT = 'DELETE_USER_EXPERIENCE_REJECT';

export const RELOAD_ALL_USER_PROFILES = 'RELOAD_ALL_USER_PROFILES';
